// lib/visitas/visitas_formato_sst.dart
//
// Formato oficial de la inspección mensual de SST (17 sep 2026). Es el
// Excel "FORMATO INSPECCIÓN SST, EXTINTOR Y BOTIQUÍN" que entregó el
// contrato, pasado a maestro de Visitas tal cual, con sus tres hojas:
//
//   F-UT-SST-02  Formato de inspección diagnóstico SST   (calificación 1/0/NA)
//   F-UT-SST-03  Inspección de extintores                (tabla por equipo, B/M/R/NC)
//   F-UT-SST-01  Formato inspección de botiquín          (sí/no, elementos con cantidad y vencimiento)
//
// Las tres se diligencian en UNA visita al mes por establecimiento y salen
// en un solo PDF (decisión del 17 sep 2026). Los ids de los ítems son
// estables: las respuestas se guardan por id, así que renumerar o
// corregir un texto aquí no puede dejar respuestas huérfanas.
//
// GENERADO desde el Excel; si el contrato entrega una versión nueva del
// formato, se vuelve a generar y se sube la versión, no se edita a mano.

import 'visitas_models.dart';

const String kFormatoSstAreaId = 'hse';
const String kFormatoSstAreaNombre = 'SST / HSE';
const String kFormatoSstNombre = 'Inspección SST, extintores y botiquín';

const String kParteSstDiagnostico = 'F-UT-SST-02';
const String kParteSstExtintores = 'F-UT-SST-03';
const String kParteSstBotiquin = 'F-UT-SST-01';

const String kTablaExtintores = 'extintores';

/// docId del formato oficial en TBL_VISITAS_FORMATOS. Fijo, para que
/// cargarlo dos veces actualice y no duplique.
String formatoSstDocId(String empresaId) => '${empresaId}_hse_sst';

VisitaFormato formatoSstOficial(String empresaId) => VisitaFormato(
  id: formatoSstDocId(empresaId),
  empresaId: empresaId,
  areaId: kFormatoSstAreaId,
  areaNombre: kFormatoSstAreaNombre,
  nombre: kFormatoSstNombre,
  predeterminado: true,
  version: 1,
  estado: kFormatoVigente,
  partes: const [
    VisitaFormatoParte(
      codigo: kParteSstDiagnostico,
      nombre: 'FORMATO DE INSPECCIÓN DIAGNÓSTICO SST',
      version: '1',
      elaboracion: '15/05/2025',
    ),
    VisitaFormatoParte(
      codigo: kParteSstExtintores,
      nombre: 'INSPECCIÓN DE EXTINTORES',
      version: '1',
      elaboracion: '16/05/2025',
    ),
    VisitaFormatoParte(
      codigo: kParteSstBotiquin,
      nombre: 'FORMATO INSPECCIÓN DE BOTIQUÍN',
      version: '1',
      elaboracion: '16/05/2025',
    ),
  ],
  tablas: const [
    VisitaFormatoTabla(
      id: kTablaExtintores,
      parte: kParteSstExtintores,
      nombre: 'Extintores',
      etiquetaFila: 'Extintor',
      camposTexto: [
        VisitaTablaCampo('ubicacion', 'Ubicación'),
        VisitaTablaCampo('tipo', 'Tipo'),
        VisitaTablaCampo('capacidad', 'Cap.'),
        VisitaTablaCampo('ultimaCarga', 'Fecha última carga'),
        VisitaTablaCampo('proximaCarga', 'Fecha próxima carga'),
        VisitaTablaCampo('numero', 'Número ident.'),
      ],
      camposEstado: [
        VisitaTablaCampo('senalizacion', 'Señalización equipo'),
        VisitaTablaCampo('estadoCilindro', 'Estado cilindro'),
        VisitaTablaCampo('pinturaCilindro', 'Pintura cilindro'),
        VisitaTablaCampo('altura', 'Altura (max 1.5 m)'),
        VisitaTablaCampo('acceso', 'Acceso al equipo'),
        VisitaTablaCampo('visibilidad', 'Visibilidad equipo'),
        VisitaTablaCampo('estadoManometro', 'Estado Manómetro'),
        VisitaTablaCampo('presionManometro', 'Presión manómetro'),
        VisitaTablaCampo('pasador', 'Pasador'),
        VisitaTablaCampo('abrazadera', 'Abrazadera pasador'),
        VisitaTablaCampo('manguera', 'Manguera o boquilla'),
        VisitaTablaCampo('sello', 'Sello de Garantía'),
        VisitaTablaCampo('manija', 'Manija de Trans.'),
      ],
    ),
  ],
  items: _items,
);

// ── Ítems ───────────────────────────────────────────────────────────────────

VisitaFormatoItem _it(
  String id,
  int orden,
  String parte,
  String seccion,
  String texto, {
  String tipo = kItemTipoCalificacion,
  String unidad = '',
  bool foto = false,
}) => VisitaFormatoItem(
  id: id,
  orden: orden,
  parte: parte,
  seccion: seccion,
  texto: texto,
  tipo: tipo,
  unidad: unidad,
  requiereEvidencia: foto,
);

final List<VisitaFormatoItem> _items = [
  // F-UT-SST-02 · Diagnóstico SST
  _it(
    'sst02_01',
    1,
    kParteSstDiagnostico,
    'CONDICIONES DE ORDEN Y ASEO',
    'Se observa organización y aseo en los pasillos, escaleras o áreas comunes (cada cosa en su lugar)?',
  ),
  _it(
    'sst02_02',
    2,
    kParteSstDiagnostico,
    'CONDICIONES DE ORDEN Y ASEO',
    '¿Se observa limpieza de equipos/implementos?',
  ),
  _it(
    'sst02_03',
    3,
    kParteSstDiagnostico,
    'CONDICIONES DE ORDEN Y ASEO',
    '¿Superficies de trabajo limpias y ordenas?',
  ),
  _it(
    'sst02_04',
    4,
    kParteSstDiagnostico,
    'CONDICIONES LOCATIVAS/FISICAS',
    '¿Se observa buenas condiciones del piso (pisos dañados, rotos, huecos u orificios sin tapar, con desniveles, etc.)',
  ),
  _it(
    'sst02_05',
    5,
    kParteSstDiagnostico,
    'CONDICIONES LOCATIVAS/FISICAS',
    '¿Se observa en buenas condiciones los pasamanos y accesos a las escaleras, las escaleras o rampas cuentas con cintas antideslizantes?',
  ),
  _it(
    'sst02_06',
    6,
    kParteSstDiagnostico,
    'CONDICIONES LOCATIVAS/FISICAS',
    '¿Las vías de acceso, transito se encuentran bien iluminadas y señalizadas (escaleras, pasillos)?',
  ),
  _it(
    'sst02_07',
    7,
    kParteSstDiagnostico,
    'CONDICIONES LOCATIVAS/FISICAS',
    '¿Se observan pasillos libres de obstáculos?',
  ),
  _it(
    'sst02_08',
    8,
    kParteSstDiagnostico,
    'CONDICIONES LOCATIVAS/FISICAS',
    '¿Techos Presentan Humedad, Deterioro, Grietas o desprendimiento?',
  ),
  _it(
    'sst02_09',
    9,
    kParteSstDiagnostico,
    'CONDICIONES LOCATIVAS/FISICAS',
    '¿Luminaria suficiente, funcionando y bien ubicada?',
  ),
  _it(
    'sst02_10',
    10,
    kParteSstDiagnostico,
    'CONDICIONES LOCATIVAS/FISICAS',
    '¿Existe buena ventilación/aireación, campana/extractor y funcionan correctamente?',
  ),
  _it(
    'sst02_11',
    11,
    kParteSstDiagnostico,
    'SITIOS DE ALMACENAMIENTO',
    '¿Las estanterías son adecuadas para el almacenamiento de materiales y están en buen estado?',
  ),
  _it(
    'sst02_12',
    12,
    kParteSstDiagnostico,
    'SITIOS DE ALMACENAMIENTO',
    '¿Se observa adecuado almacenamiento de implementos, herramientas, equipos, sustancias peligrosas, entre otros; y este se considera seguro?',
  ),
  _it(
    'sst02_13',
    13,
    kParteSstDiagnostico,
    'SITIOS DE ALMACENAMIENTO',
    '¿Se observa adecuada manipulación de implementos, herramientas, equipos, sustancias peligrosas, entre otros?',
  ),
  _it(
    'sst02_14',
    14,
    kParteSstDiagnostico,
    'SITIOS DE ALMACENAMIENTO',
    '¿Se observa buen estado de los implementos, herramientas, equipos, sustancias peligrosas, entre otras?',
  ),
  _it(
    'sst02_15',
    15,
    kParteSstDiagnostico,
    'CONDICIONES ELÉCTRICAS',
    '¿Existen conexiones sobrecargadas (tomas sobrecargadas)?',
  ),
  _it(
    'sst02_16',
    16,
    kParteSstDiagnostico,
    'CONDICIONES ELÉCTRICAS',
    '¿Los cables de maquinas o extensiones están en buen estado y no sueltos por el piso?',
  ),
  _it(
    'sst02_17',
    17,
    kParteSstDiagnostico,
    'CONDICIONES ELÉCTRICAS',
    '¿Las tomas e interruptores están en buen estado, funcionando y con sus tapas protectoras?',
  ),
  _it(
    'sst02_18',
    18,
    kParteSstDiagnostico,
    'CONDICIONES ELÉCTRICAS',
    '¿Existe línea o polo a tierra?',
  ),
  _it(
    'sst02_19',
    19,
    kParteSstDiagnostico,
    'CONDICIONES ELÉCTRICAS',
    '¿Las cajas eléctricas o tableros de distribución están sin obstáculos, claramente señalizadas, con cerradura y limpios?',
  ),
  _it(
    'sst02_20',
    20,
    kParteSstDiagnostico,
    'PRODUCTOS QUÍMICOS Y SUSTANCIAS PELIGROSAS',
    '¿Los lugares destinados para almacenamiento de productos químicos están separados en un área independiente y cuenta con ventilación e iluminación adecuada?',
  ),
  _it(
    'sst02_21',
    21,
    kParteSstDiagnostico,
    'PRODUCTOS QUÍMICOS Y SUSTANCIAS PELIGROSAS',
    '¿Los recipientes con productos químicos están rotulados, tienen Ficha técnica, FDS y matriz de compatibilidad en el sitio?',
  ),
  _it(
    'sst02_22',
    22,
    kParteSstDiagnostico,
    'PRODUCTOS QUÍMICOS Y SUSTANCIAS PELIGROSAS',
    '¿Se cuenta con la hoja de datos de seguridad del producto químico, esta vigente, actualizada con SGA y en el sitio de productos químicos?',
  ),
  _it(
    'sst02_23',
    23,
    kParteSstDiagnostico,
    'PRODUCTOS QUÍMICOS Y SUSTANCIAS PELIGROSAS',
    '¿El personal tiene conocimiento de que es una FDS, que hacer en caso de emergencia y EPP que deben utilizar?',
  ),
  _it(
    'sst02_24',
    24,
    kParteSstDiagnostico,
    'PRODUCTOS QUÍMICOS Y SUSTANCIAS PELIGROSAS',
    '¿Se cuentan los productos químicos almacenados sobre estibas antiderrames?',
  ),
  _it(
    'sst02_25',
    25,
    kParteSstDiagnostico,
    'PRODUCTOS QUÍMICOS Y SUSTANCIAS PELIGROSAS',
    '¿se cuenta con Kit de derrame cuando aplique?',
  ),
  _it(
    'sst02_26',
    26,
    kParteSstDiagnostico,
    'SANEAMIENTO BÁSICO',
    '¿Se hace manejo y control de plagas (ratones, cucarachas, mosquitos, etc.?',
  ),
  _it(
    'sst02_27',
    27,
    kParteSstDiagnostico,
    'SANEAMIENTO BÁSICO',
    '¿Se cuenta con buen suministro de energía y agua?',
  ),
  _it(
    'sst02_28',
    28,
    kParteSstDiagnostico,
    'SANEAMIENTO BÁSICO',
    '¿Se encuentran en buen estado las llaves de gas, llaves de registros de agua, baños o demás elementos dispensadores de agua (libres de fugas visibles o desperdicio de liquido)?',
  ),
  _it(
    'sst02_29',
    29,
    kParteSstDiagnostico,
    'SANEAMIENTO BÁSICO',
    '¿Se cuenta con lockers suficientes para el personal y están en buenas condiciones?',
  ),
  _it(
    'sst02_30',
    30,
    kParteSstDiagnostico,
    'SANEAMIENTO BÁSICO',
    '¿Los cárcamos están limpios, sin agua posada en los mismos, las rejillas cuentan con sus tapas protectoras o están completas y son seguras?',
  ),
  _it(
    'sst02_31',
    31,
    kParteSstDiagnostico,
    'EQUIPOS PARA ATENCIÓN DE EMERGENCIAS y PREPARACIÓN DE EMERGENCIAS',
    '¿Se cuenta con extintores de tipo CO2, K y multipropósito, el personal conoce la ubicación de los extintores y sabe como utilizarlos?',
    foto: true,
  ),
  _it(
    'sst02_32',
    32,
    kParteSstDiagnostico,
    'EQUIPOS PARA ATENCIÓN DE EMERGENCIAS y PREPARACIÓN DE EMERGENCIAS',
    '¿Los Extintores se encuentran debidamente recargados, vigentes y existe hoja de vida de su revisión y mantenimiento?',
    foto: true,
  ),
  _it(
    'sst02_33',
    33,
    kParteSstDiagnostico,
    'EQUIPOS PARA ATENCIÓN DE EMERGENCIAS y PREPARACIÓN DE EMERGENCIAS',
    '¿Los Extintores son suficientes, uno cada 15 metros (promedio según Norma NFPA 10, con la señalización, a mínimo 1.5 altura o en su base soporte?',
    foto: true,
  ),
  _it(
    'sst02_34',
    34,
    kParteSstDiagnostico,
    'EQUIPOS PARA ATENCIÓN DE EMERGENCIAS y PREPARACIÓN DE EMERGENCIAS',
    '¿Se cuenta con la manta anti fuego cerca a los equipos de cocción?',
    foto: true,
  ),
  _it(
    'sst02_35',
    35,
    kParteSstDiagnostico,
    'EQUIPOS PARA ATENCIÓN DE EMERGENCIAS y PREPARACIÓN DE EMERGENCIAS',
    '¿Se cuenta con mínimo un brigadista capacitado en el establecimiento y el personal conoce quien es, sus funciones?',
    foto: true,
  ),
  _it(
    'sst02_36',
    36,
    kParteSstDiagnostico,
    'EQUIPOS PARA ATENCIÓN DE EMERGENCIAS y PREPARACIÓN DE EMERGENCIAS',
    'El personal sabe a donde dirigirse en caso de evacuación, punto de encuentro, sabe como actuar en caso de cada emergencia y conoce los PON´S?',
    foto: true,
  ),
  _it(
    'sst02_37',
    37,
    kParteSstDiagnostico,
    'EQUIPOS PARA ATENCIÓN DE EMERGENCIAS y PREPARACIÓN DE EMERGENCIAS',
    '¿Se cuenta con botiquín de primeros auxilios tipo A o B de acuerdo a el establecimiento?',
    foto: true,
  ),
  _it(
    'sst02_38',
    38,
    kParteSstDiagnostico,
    'MAQUINAS Y HERRAMIENTAS',
    '¿Están limpias, en el lugar correspondiente, con señalización y ficha técnica publicada en el área?',
  ),
  _it(
    'sst02_39',
    39,
    kParteSstDiagnostico,
    'MAQUINAS Y HERRAMIENTAS',
    '¿Las maquinas cuentan con su registro de mtto preventivo o correctivo?',
  ),
  _it(
    'sst02_40',
    40,
    kParteSstDiagnostico,
    'MAQUINAS Y HERRAMIENTAS',
    '¿Las maquinas o equipos cuentan con sus protecciones y funcionamiento normal?',
  ),
  _it(
    'sst02_41',
    41,
    kParteSstDiagnostico,
    'MAQUINAS Y HERRAMIENTAS',
    '¿Se realizan las inspecciones preoperacionales de las maquinas y equipos?',
  ),
  _it(
    'sst02_42',
    42,
    kParteSstDiagnostico,
    'MAQUINAS Y HERRAMIENTAS',
    '¿El personal cuenta con los EPP, formación o capacitación para operación de la misma?',
  ),
  _it(
    'sst02_43',
    43,
    kParteSstDiagnostico,
    'RESIDUOS Y DESECHOS',
    '¿Existe punto de acopio temporal techado y separado de las demás áreas para la dispoción de los residuos?',
  ),
  _it(
    'sst02_44',
    44,
    kParteSstDiagnostico,
    'RESIDUOS Y DESECHOS',
    '¿Los contenedores manejan bolsas en su interior para el almacenamiento de los residuos, son los colores correspondientes según la clasificación?',
  ),
  _it(
    'sst02_45',
    45,
    kParteSstDiagnostico,
    'RESIDUOS Y DESECHOS',
    '¿El área de almacenamiento se encuentra señalizado, ordenado y clasificado adecuadamente?',
  ),
  _it(
    'sst02_46',
    46,
    kParteSstDiagnostico,
    'RESIDUOS Y DESECHOS',
    '¿El punto de acopio se encuentra libre de vectores y roedores?',
  ),
  _it(
    'sst02_47',
    47,
    kParteSstDiagnostico,
    'RESIDUOS Y DESECHOS',
    '¿Se llevan registro de los residuos generados?',
  ),
  _it(
    'sst02_48',
    48,
    kParteSstDiagnostico,
    'PREVENCION DE HERIDAS',
    '¿Según la tarea se selecciona la herramienta adecuada para el trabajo a realizar?',
  ),
  _it(
    'sst02_49',
    49,
    kParteSstDiagnostico,
    'PREVENCION DE HERIDAS',
    '¿Se usan cuchillos y están siendo previamente afilados para realizar las tareas?',
  ),
  _it(
    'sst02_50',
    50,
    kParteSstDiagnostico,
    'PREVENCION DE HERIDAS',
    '¿Existe lugar de almacenamiento de cuchillos o bisturí (barra con imán, caja de herramientas, estuche o porta herramientas) y con acceso limitado?',
  ),
  _it(
    'sst02_51',
    51,
    kParteSstDiagnostico,
    'PREVENCION DE HERIDAS',
    '¿Se utilizan los EPP adecuados para la labor, la persona sabe donde esta ubicado el botiquín sabe que hacer en caso de un AT?',
  ),
  _it(
    'sst02_52',
    52,
    kParteSstDiagnostico,
    'PREVENCION DE QUEMADURAS',
    '¿Para realizar el oficio o manipulación de utensilios, herramientas o equipos calientes se utilizan elementos de protección (careta, gafas, guantes, peto, mangas de protección?',
  ),
  _it(
    'sst02_53',
    53,
    kParteSstDiagnostico,
    'PREVENCION DE QUEMADURAS',
    '¿Al transportar utensilios, herramientas o equipos calientes existen carros transportadores u otro medio de apoyo?',
  ),
  _it(
    'sst02_54',
    54,
    kParteSstDiagnostico,
    'PREVENCION DE QUEMADURAS',
    '¿Se utilizan pinzas, guantes otras herramientas de apoyo para manipular objetos calientes?',
  ),
  _it(
    'sst02_55',
    55,
    kParteSstDiagnostico,
    'PREVENCIÓN DOLOR LUMBAR',
    '¿El almacenamiento de artículos de mayor peso o de uso mas frecuente se almacenan en la parte inferior, ya sea en la estantería o en estiba libre?',
  ),
  _it(
    'sst02_56',
    56,
    kParteSstDiagnostico,
    'PREVENCIÓN DOLOR LUMBAR',
    '¿El levantamiento y transporte de materiales, utensilios, equipos por encima del límite permisible se hace con ayuda de otras personas o con algún medio de transporte?',
  ),
  _it(
    'sst02_57',
    57,
    kParteSstDiagnostico,
    'PREVENCIÓN DOLOR LUMBAR',
    '¿Se cuenta con escalera para alcanzar los objetos ubicados por encima de los hombros, las escaleras de acceso están en buen estado y ancladas?',
  ),
  _it(
    'sst02_58',
    58,
    kParteSstDiagnostico,
    'PREVENCIÓN DOLOR LUMBAR',
    '¿Se realiza el manejo adecuado de cargas: Flexión de piernas y no flexión de columna, se realizan pausas activas durante la jornada laboral?',
  ),
  _it(
    'sst02_59',
    59,
    kParteSstDiagnostico,
    'PREVENCIÓN DOLOR LUMBAR',
    '¿Los puestos de trabajo son ergonómicos para las labores a realizar?',
  ),
  _it(
    'sst02_60',
    60,
    kParteSstDiagnostico,
    'ELEMENTOS DE PROTECCIÓN PERSONAL (EPP)',
    'Existe matriz de elementos de protección personal para la operación y los riesgos asociados a las tareas.',
  ),
  _it(
    'sst02_61',
    61,
    kParteSstDiagnostico,
    'ELEMENTOS DE PROTECCIÓN PERSONAL (EPP)',
    'Los EPP se utilizan y se les da el mantenimiento definido por el manual del fabricante y se utilizan los EPP mínimos para el área (Delantal industrial, chaqueta térmica para cuarto frio, guante de malla de acero para porcionadores de proteína, careta de esmeril para frituras cuando aplique y gafas de seguridad transparentes para actividades de limpieza?',
  ),
  _it(
    'sst02_62',
    62,
    kParteSstDiagnostico,
    'ELEMENTOS DE PROTECCIÓN PERSONAL (EPP)',
    'Se diligencia y se mantiene al día el registro de entrega de EPP',
  ),
  _it(
    'sst02_63',
    63,
    kParteSstDiagnostico,
    'ELEMENTOS DE PROTECCIÓN PERSONAL (EPP)',
    'Existe lugar de almacenamiento de los EPP (En el caso de alimentos se mantienen separados los guantes de alimentos de los de loza)',
  ),
  _it(
    'sst02_64',
    64,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    '¿Se realizo la identificación de peligros y valoración de riesgos en los sitios de trabajo?',
  ),
  _it(
    'sst02_65',
    65,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'Los Exámenes periódicos se encuentran al día. ( Solicitar el listado de colaboradores y pedir al azar una muestra)',
  ),
  _it(
    'sst02_66',
    66,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    '¿Se realizaron las capacitaciones mensuales aplicables al SG-SST?',
  ),
  _it(
    'sst02_67',
    67,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    '¿Los colaboradores conocen el procedimiento y en el contrato se cuenta con formatos para reporte e investigación de accidentes, incidentes/ lesiones menores?',
  ),
  _it(
    'sst02_68',
    68,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    '¿Se cuenta con el botiquín de primeros auxilios, el cual contiene los elementos aprobados por el área de HSE y personal competente para la atención de primeros auxilios?',
  ),
  _it(
    'sst02_69',
    69,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'Se realizo investigación y plan de acción de los accidente ocurridos en el periodo fiscal actual (si aplica)',
  ),
  _it(
    'sst02_70',
    70,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'El administrador lleva los registros de los Indicadores de HSE.',
  ),
  _it(
    'sst02_71',
    71,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'Se encuentra publicado el Reglamento Higiene y Seguridad Industrial.',
  ),
  _it(
    'sst02_72',
    72,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    '¿Se encuentra publicada, vigente, firmada y fechada la política de HSE?',
  ),
  _it(
    'sst02_73',
    73,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'Se cuenta con registro de actividades del plan de emergencias realizadas por la operación o el cliente de acuerdo a las necesidades de la operación.',
  ),
  _it(
    'sst02_74',
    74,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'Se cuenta con COPASST y el personal conoce del mismo y participa',
  ),
  _it(
    'sst02_75',
    75,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'Se cuenta con copia de los pagos de la Seguridad Social, al día.',
  ),
  _it(
    'sst02_76',
    76,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'Se cuenta con copia de la matriz de requisitos legales actualizada.',
  ),
  _it(
    'sst02_77',
    77,
    kParteSstDiagnostico,
    'OTROS ASPECTOS LEGALES Y DE GESTION',
    'Se cuenta con Cronograma de Actividades de HSE. Especifico para la operación.',
  ),
  // F-UT-SST-01 · Botiquín
  _it(
    'sst01_c1',
    78,
    kParteSstBotiquin,
    'BOTIQUÍN',
    '¿El botiquín esta en su lugar?',
    tipo: kItemTipoSiNo,
  ),
  _it(
    'sst01_c2',
    79,
    kParteSstBotiquin,
    'BOTIQUÍN',
    '¿El botiquín se encuentra señalizado y en su soporte o lugar de almacenamiento?',
    tipo: kItemTipoSiNo,
  ),
  _it(
    'sst01_c3',
    80,
    kParteSstBotiquin,
    'BOTIQUÍN',
    '¿Todos los elementos están debidamente empacados y marcados?',
    tipo: kItemTipoSiNo,
  ),
  _it(
    'sst01_c4',
    81,
    kParteSstBotiquin,
    'BOTIQUÍN',
    '¿Se encuentran en buen estado de conservación (limpieza-pintura)?',
    tipo: kItemTipoSiNo,
  ),
  _it(
    'sst01_e01',
    82,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Esparadrapo de tela rollo 4"',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e02',
    83,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Gasa estéril',
    tipo: kItemTipoElemento,
    unidad: 'Paquete X 3',
  ),
  _it(
    'sst01_e03',
    84,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Gasas limpias Precortada',
    tipo: kItemTipoElemento,
    unidad: 'Paquete x 20',
  ),
  _it(
    'sst01_e04',
    85,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Curas',
    tipo: kItemTipoElemento,
    unidad: '5 Unidades',
  ),
  _it(
    'sst01_e05',
    86,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Micropore',
    tipo: kItemTipoElemento,
    unidad: 'Rollo',
  ),
  _it(
    'sst01_e06',
    87,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Apósitos o compresas no estériles',
    tipo: kItemTipoElemento,
    unidad: '4 Unidad',
  ),
  _it(
    'sst01_e07',
    88,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Venda de algodón 3x5 Yardas',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e08',
    89,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Venda de algodón 5x5 Yardas',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e09',
    90,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Venda elásticas 2x5 Yardas',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e10',
    91,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Venda elásticas 3x5 Yardas',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e11',
    92,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Venda elásticas 5x5 Yardas',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e12',
    93,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Jeringa',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e13',
    94,
    kParteSstBotiquin,
    'ELEMENTOS BOTIQUÍN TIPO A',
    'Bajalenguas',
    tipo: kItemTipoElemento,
    unidad: 'Paquete x 20',
  ),
  _it(
    'sst01_e14',
    95,
    kParteSstBotiquin,
    'ANTISÉPTICOS',
    'Alcohol antiséptico frasco por 275 ml',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e15',
    96,
    kParteSstBotiquin,
    'ANTISÉPTICOS',
    'Yodopovidona (Jabón Quirúrgico)',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e16',
    97,
    kParteSstBotiquin,
    'ANTISÉPTICOS',
    'Yodopovidona (Solución) OPCIONAL',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e17',
    98,
    kParteSstBotiquin,
    'ANTISÉPTICOS',
    'Solución salina 250 ml o 500 ml',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e18',
    99,
    kParteSstBotiquin,
    'ELEMENTOS ESPECÍFICOS PARA ATENCIÓN DE EMERGENCIAS',
    'Guantes de Látex',
    tipo: kItemTipoElemento,
    unidad: '5 Unidades',
  ),
  _it(
    'sst01_e19',
    100,
    kParteSstBotiquin,
    'ELEMENTOS ESPECÍFICOS PARA ATENCIÓN DE EMERGENCIAS',
    'Tapabocas',
    tipo: kItemTipoElemento,
    unidad: '5 Unidades',
  ),
  _it(
    'sst01_e20',
    101,
    kParteSstBotiquin,
    'ELEMENTOS ESPECÍFICOS PARA ATENCIÓN DE EMERGENCIAS',
    'Termómetro digital',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e21',
    102,
    kParteSstBotiquin,
    'ELEMENTOS ESPECÍFICOS PARA ATENCIÓN DE EMERGENCIAS',
    'Camilla',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e22',
    103,
    kParteSstBotiquin,
    'ELEMENTOS ESPECÍFICOS PARA ATENCIÓN DE EMERGENCIAS',
    'Inmovilizadores: cervical, miembros superiores, miembros inferiores',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e23',
    104,
    kParteSstBotiquin,
    'ELEMENTOS ESPECÍFICOS PARA ATENCIÓN DE EMERGENCIAS',
    'Pito',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e24',
    105,
    kParteSstBotiquin,
    'ELEMENTOS ESPECÍFICOS PARA ATENCIÓN DE EMERGENCIAS',
    'Linterna con Pilas',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_e25',
    106,
    kParteSstBotiquin,
    'ELEMENTOS ESPECÍFICOS PARA ATENCIÓN DE EMERGENCIAS',
    'Tijeras',
    tipo: kItemTipoElemento,
    unidad: '1 Unidad',
  ),
  _it(
    'sst01_cam1',
    107,
    kParteSstBotiquin,
    'CONDICIONES DE LA CAMILLA',
    'Señalización y ubicación correcta',
    tipo: kItemTipoSiNo,
  ),
  _it(
    'sst01_cam2',
    108,
    kParteSstBotiquin,
    'CONDICIONES DE LA CAMILLA',
    'Estado de la camilla',
    tipo: kItemTipoSiNo,
  ),
  _it(
    'sst01_cam3',
    109,
    kParteSstBotiquin,
    'CONDICIONES DE LA CAMILLA',
    'Correas de ajuste en buen estado',
    tipo: kItemTipoSiNo,
  ),
];
