// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0YxkcePFqXJah5Om22ocaXSyCMzLz9NQ',
    appId: '1:379551786878:web:bfdce56a6b9454b984352f',
    messagingSenderId: '379551786878',
    projectId: 'integra360-94704',
    authDomain: 'integra360-94704.firebaseapp.com',
    databaseURL: 'https://integra360-94704-default-rtdb.firebaseio.com',
    storageBucket: 'integra360-94704.firebasestorage.app',
    measurementId: 'G-G74NMJWNSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZna3nMuCU8BxpaJbfjFKyT4A0hM4fya4',
    appId: '1:379551786878:android:5ff74c61ef72e7ad84352f',
    messagingSenderId: '379551786878',
    projectId: 'integra360-94704',
    databaseURL: 'https://integra360-94704-default-rtdb.firebaseio.com',
    storageBucket: 'integra360-94704.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_VXHlHj_bCZaOaJ2tkK4Lr4s970vI-8',
    appId: '1:379551786878:ios:b2f6d4777de370c884352f',
    messagingSenderId: '379551786878',
    projectId: 'integra360-94704',
    databaseURL: 'https://integra360-94704-default-rtdb.firebaseio.com',
    storageBucket: 'integra360-94704.firebasestorage.app',
    iosBundleId: 'com.example.capitalUspec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_VXHlHj_bCZaOaJ2tkK4Lr4s970vI-8',
    appId: '1:379551786878:ios:b2f6d4777de370c884352f',
    messagingSenderId: '379551786878',
    projectId: 'integra360-94704',
    databaseURL: 'https://integra360-94704-default-rtdb.firebaseio.com',
    storageBucket: 'integra360-94704.firebasestorage.app',
    iosBundleId: 'com.example.capitalUspec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0YxkcePFqXJah5Om22ocaXSyCMzLz9NQ',
    appId: '1:379551786878:web:54070bc61d206bb284352f',
    messagingSenderId: '379551786878',
    projectId: 'integra360-94704',
    authDomain: 'integra360-94704.firebaseapp.com',
    databaseURL: 'https://integra360-94704-default-rtdb.firebaseio.com',
    storageBucket: 'integra360-94704.firebasestorage.app',
    measurementId: 'G-CDN4CZESZ6',
  );

}