// lib/compras/compras_req_seed.dart
// Datos de siembra de TBL_COMPRAS_REQ_DOCUMENTOS.
// Fuente: PARAMETRIZACION_DE_PRODUCTOS_AJUSTADO_v3.xlsx — Hoja REQ_DOCUMENTOS.
// 76 filas de requisitos documentales.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'compras_req_engine.dart';
import 'compras_service.dart';

// ══════════════════════════════════════════════════════════════════════════════
// Datos fuente (76 filas del Excel)
// Columnas: categoriaApp | materiaPrima | origen | nivel | etapa |
//           codDoc | keyApp | documentoRequerido | obligatorio |
//           condicion | norma | entidad | frecuencia
// ══════════════════════════════════════════════════════════════════════════════

const List<Map<String, String>> kReqDocumentosData = [
  // ─── PROTEÍNA — CARNE DE RES / CERDO / POLLO NO MARINADO — NACIONAL — PROVEEDOR
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_FICHA_TECNICA',
    'keyApp': 'fichaTecnicaProv',
    'documentoRequerido': 'Ficha técnica del producto',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_RUT',
    'keyApp': 'rut',
    'documentoRequerido': 'RUT del proveedor',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CAMARA_COMERCIO',
    'keyApp': 'camaraComercio',
    'documentoRequerido': 'Cámara de comercio vigente',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_PLANTA',
    'keyApp': 'actaIvcPlanta',
    'documentoRequerido': 'Acta IVC planta de producción (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': 'Autoridad sanitaria',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_VEHICULO',
    'keyApp': 'actaIvcVehiculo',
    'documentoRequerido': 'Acta IVC del vehículo transportador (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': 'Autoridad sanitaria',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_EXAMEN_MEDICO_CONDUCTOR',
    'keyApp': 'examenMedico',
    'documentoRequerido': 'Examen médico del conductor con énfasis en alimentos',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CURSO_MANIPULACION',
    'keyApp': 'cursoManipulacion',
    'documentoRequerido':
        'Certificado/curso de manipulación de alimentos del conductor/manipulador',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  // ─── PROTEÍNA — CARNE DE RES / CERDO / POLLO NO MARINADO — NACIONAL — RECEPCION
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_GUIA_TRANSPORTE',
    'keyApp': 'guiaTransporte',
    'documentoRequerido': 'Guía de transporte',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_GUIA_SACRIFICIO',
    'keyApp': 'guiaSacrificio',
    'documentoRequerido': 'Guía de sacrificio',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_CERT_CALIDAD',
    'keyApp': 'certCalidad',
    'documentoRequerido': 'Certificado de calidad',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_FICHA_TECNICA',
    'keyApp': 'fichaTecnica',
    'documentoRequerido': 'Ficha técnica (copia vigente)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'CARNE DE RES, CARNE DE CERDO, POLLO NO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_EVIDENCIA_ETIQUETA',
    'keyApp': 'evidenciaEtiqueta',
    'documentoRequerido': 'Evidencia fotográfica del rótulo/etiqueta del empaque',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  // ─── TODAS — TODAS — AMBOS — RECEPCION — ROTULADO
  {
    'categoriaApp': 'Todas',
    'materiaPrima': 'TODAS',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_FECHA_VENCIMIENTO',
    'keyApp': 'fechaVencimientoEtiqueta',
    'documentoRequerido':
        'Fecha de vencimiento impresa en el empaque (verificación/evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 5109 de 2005',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  // ─── PROTEÍNA — PROTEÍNAS (CERDO/PESCADO/POLLO) — IMPORTADO — RECEPCION
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'IMP_DECLARACION_IMPORTACION',
    'keyApp': 'declImport',
    'documentoRequerido': 'Declaración de Importación (DIAN)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma':
        'Decreto 1500 de 2007; Resolución 240 de 2013; Resolución 241 de 2013; Resolución 242 de 2013',
    'entidad': 'DIAN',
    'frecuencia': 'POR_IMPORTACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'IMP_DOC_TRANSPORTE',
    'keyApp': 'docTransporte',
    'documentoRequerido': 'Documento de transporte (BL/AWB/Carta porte)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma':
        'Decreto 1500 de 2007; Resolución 240 de 2013; Resolución 241 de 2013; Resolución 242 de 2013',
    'entidad': '',
    'frecuencia': 'POR_IMPORTACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'IMP_MANDATO_AGENTE_ADUANAS',
    'keyApp': 'mandatoAduanas',
    'documentoRequerido': 'Mandato o poder del agente de aduanas',
    'obligatorio': 'CONDICIONAL',
    'condicion': 'Si aplica (cuando interviene agente de aduanas)',
    'norma':
        'Decreto 1500 de 2007; Resolución 240 de 2013; Resolución 241 de 2013; Resolución 242 de 2013',
    'entidad': '',
    'frecuencia': 'POR_IMPORTACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'IMP_CERT_SANITARIA',
    'keyApp': 'certSanitariaImport',
    'documentoRequerido': 'Certificación sanitaria de importación',
    'obligatorio': 'SI',
    'condicion': '',
    'norma':
        'Decreto 1500 de 2007; Resolución 240 de 2013; Resolución 241 de 2013; Resolución 242 de 2013',
    'entidad': '',
    'frecuencia': 'POR_IMPORTACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'IMP_PERMISO_ZOO_ICA',
    'keyApp': 'permisoZoo',
    'documentoRequerido': 'Permiso Zoosanitario de Importación',
    'obligatorio': 'SI',
    'condicion': '',
    'norma':
        'Decreto 1500 de 2007; Resolución 240 de 2013; Resolución 241 de 2013; Resolución 242 de 2013',
    'entidad': 'ICA',
    'frecuencia': 'POR_IMPORTACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'IMP_VISTO_BUENO_INVIMA',
    'keyApp': 'vistoInvima',
    'documentoRequerido': 'Visto Bueno Sanitario',
    'obligatorio': 'SI',
    'condicion': '',
    'norma':
        'Decreto 1500 de 2007; Resolución 240 de 2013; Resolución 241 de 2013; Resolución 242 de 2013',
    'entidad': 'INVIMA',
    'frecuencia': 'POR_IMPORTACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'IMP_FICHA_TECNICA_ES',
    'keyApp': 'fichaTecnicaEs',
    'documentoRequerido': 'Ficha técnica de la materia prima en español',
    'obligatorio': 'SI',
    'condicion': '',
    'norma':
        'Decreto 1500 de 2007; Resolución 240 de 2013; Resolución 241 de 2013; Resolución 242 de 2013',
    'entidad': '',
    'frecuencia': 'POR_IMPORTACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_ETIQUETA_ES',
    'keyApp': 'etiquetaEspanol',
    'documentoRequerido': 'Etiqueta en idioma español (evidencia fotográfica)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Decreto 1500 de 2007; Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'POR_IMPORTACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'PROTEÍNAS (CARNE DE CERDO, PESCADO Y POLLO)',
    'origen': 'IMPORTADO',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_INFO_ORIGEN_IMPORT',
    'keyApp': 'rotuladoImportOrigen',
    'documentoRequerido':
        'Rotulado: información obligatoria incluyendo país de origen (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 240 de 2013',
    'entidad': '',
    'frecuencia': 'POR_IMPORTACION',
  },
  // ─── PROTEÍNA — POLLO MARINADO — NACIONAL — PROVEEDOR
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_FICHA_TECNICA_RS',
    'keyApp': 'fichaTecnicaProv',
    'documentoRequerido': 'Ficha técnica con registro sanitario',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': 'INVIMA',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_RUT',
    'keyApp': 'rut',
    'documentoRequerido': 'RUT del proveedor',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CAMARA_COMERCIO',
    'keyApp': 'camaraComercio',
    'documentoRequerido': 'Cámara de comercio vigente',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_PLANTA',
    'keyApp': 'actaIvcPlanta',
    'documentoRequerido': 'Acta IVC planta de producción (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_VEHICULO',
    'keyApp': 'actaIvcVehiculo',
    'documentoRequerido': 'Acta IVC del vehículo transportador (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_EXAMEN_MEDICO_CONDUCTOR',
    'keyApp': 'examenMedico',
    'documentoRequerido': 'Examen médico del conductor con énfasis en alimentos',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CURSO_MANIPULACION',
    'keyApp': 'cursoManipulacion',
    'documentoRequerido':
        'Certificado/curso de manipulación de alimentos del conductor/manipulador',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  // ─── PROTEÍNA — POLLO MARINADO — NACIONAL — RECEPCION
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_GUIA_TRANSPORTE',
    'keyApp': 'guiaTransporte',
    'documentoRequerido': 'Guía de transporte',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_GUIA_SACRIFICIO',
    'keyApp': 'guiaSacrificio',
    'documentoRequerido': 'Guía de sacrificio',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_CERT_CALIDAD',
    'keyApp': 'certCalidad',
    'documentoRequerido': 'Certificado de calidad',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_FICHA_TECNICA_RS',
    'keyApp': 'fichaTecnica',
    'documentoRequerido': 'Ficha técnica con registro sanitario (copia vigente)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_DENOMINACION',
    'keyApp': 'rotuladoDenominacion',
    'documentoRequerido': 'Denominación del producto (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_INGREDIENTES',
    'keyApp': 'rotuladoIngredientes',
    'documentoRequerido':
        'Lista de ingredientes y declaración de agua añadida (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_ADITIVOS',
    'keyApp': 'rotuladoAditivos',
    'documentoRequerido': 'Declaración de aditivos',
    'obligatorio': 'CONDICIONAL',
    'condicion': 'Si aplica (si contiene aditivos)',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_DATOS_LOTE_FECHAS',
    'keyApp': 'rotuladoLoteFechas',
    'documentoRequerido':
        'Rotulado: lote, peso neto, fechas, conservación y datos del fabricante (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Proteína',
    'materiaPrima': 'POLLO MARINADO',
    'origen': 'NACIONAL',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_REG_SANITARIO_INVIMA',
    'keyApp': 'rotuladoRegistroInvima',
    'documentoRequerido': 'Registro sanitario INVIMA visible en etiqueta (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013',
    'entidad': 'INVIMA',
    'frecuencia': 'POR_PEDIDO',
  },
  // ─── ABARROTES — QUESO / SALCHICHA / PULPAS DE FRUTA — AMBOS — PROVEEDOR
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_FICHA_TECNICA_RS',
    'keyApp': 'fichaTecnicaProv',
    'documentoRequerido': 'Ficha técnica con registro sanitario',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': 'INVIMA',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_RUT',
    'keyApp': 'rut',
    'documentoRequerido': 'RUT del proveedor',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CAMARA_COMERCIO',
    'keyApp': 'camaraComercio',
    'documentoRequerido': 'Cámara de comercio vigente',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_PLANTA',
    'keyApp': 'actaIvcPlanta',
    'documentoRequerido': 'Acta IVC planta de producción (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_SOPORTE_REG_SAN',
    'keyApp': 'soporteRegistroInvima',
    'documentoRequerido': 'Soporte de registro sanitario INVIMA',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': 'INVIMA',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_VEHICULO',
    'keyApp': 'actaIvcVehiculo',
    'documentoRequerido': 'Acta IVC del vehículo transportador (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_EXAMEN_MEDICO_CONDUCTOR',
    'keyApp': 'examenMedico',
    'documentoRequerido': 'Examen médico del conductor con énfasis en alimentos',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CURSO_MANIPULACION',
    'keyApp': 'cursoManipulacion',
    'documentoRequerido':
        'Certificado/curso de manipulación de alimentos del conductor/manipulador',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  // ─── ABARROTES — QUESO / SALCHICHA / PULPAS DE FRUTA — AMBOS — RECEPCION
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_CERT_CALIDAD',
    'keyApp': 'certCalidad',
    'documentoRequerido': 'Certificado de calidad',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_FICHA_TECNICA_RS',
    'keyApp': 'fichaTecnica',
    'documentoRequerido': 'Ficha técnica con registro sanitario (copia vigente)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_ETIQUETA_INFO_BASICA',
    'keyApp': 'rotuladoInfoBasica',
    'documentoRequerido':
        'Rotulado: nombre alimento, contenido neto, fabricante/fraccionador, lote, vencimiento, conservación, ciudad, etc. (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_ADVERTENCIAS',
    'keyApp': 'rotuladoAdvertencias',
    'documentoRequerido':
        'Rotulado: advertencias (alérgenos, sodio, azúcares, etc.) (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2013; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'QUESO / SALCHICHA / PULPAS DE FRUTA',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_ETIQ_FRONTAL_810',
    'keyApp': 'rotuladoFrontal810',
    'documentoRequerido': 'Etiquetado nutricional frontal (evidencia)',
    'obligatorio': 'CONDICIONAL',
    'condicion':
        'Si el producto está sujeto a etiquetado frontal (Res. 810/2021)',
    'norma': 'Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  // ─── ABARROTES — ABARROTES — AMBOS — PROVEEDOR
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_FICHA_TECNICA_RS',
    'keyApp': 'fichaTecnicaProv',
    'documentoRequerido': 'Ficha técnica con registro sanitario',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': 'INVIMA',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_RUT',
    'keyApp': 'rut',
    'documentoRequerido': 'RUT del proveedor',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CAMARA_COMERCIO',
    'keyApp': 'camaraComercio',
    'documentoRequerido': 'Cámara de comercio vigente',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_SOPORTE_REG_SAN',
    'keyApp': 'soporteRegistroInvima',
    'documentoRequerido': 'Soporte de registro sanitario INVIMA',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': 'INVIMA',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_PLANTA',
    'keyApp': 'actaIvcPlanta',
    'documentoRequerido': 'Acta IVC planta de producción (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_VEHICULO',
    'keyApp': 'actaIvcVehiculo',
    'documentoRequerido': 'Acta IVC del vehículo transportador (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_EXAMEN_MEDICO_CONDUCTOR',
    'keyApp': 'examenMedico',
    'documentoRequerido': 'Examen médico del conductor con énfasis en alimentos',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CURSO_MANIPULACION',
    'keyApp': 'cursoManipulacion',
    'documentoRequerido':
        'Certificado/curso de manipulación de alimentos del conductor/manipulador',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  // ─── ABARROTES — ABARROTES — AMBOS — RECEPCION
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_FICHA_TECNICA_RS',
    'keyApp': 'fichaTecnica',
    'documentoRequerido': 'Ficha técnica con registro sanitario (copia vigente)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_ETIQUETA_INFO_BASICA',
    'keyApp': 'rotuladoInfoBasica',
    'documentoRequerido':
        'Rotulado: nombre, contenido, fabricante/fraccionador, lote, vencimiento, conservación, ciudad, etc. (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Resolución 2674 de 2014; Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Abarrotes',
    'materiaPrima': 'ABARROTES',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_ETIQ_FRONTAL_810',
    'keyApp': 'rotuladoFrontal810',
    'documentoRequerido': 'Etiquetado nutricional frontal (evidencia)',
    'obligatorio': 'CONDICIONAL',
    'condicion':
        'Si el producto está sujeto a etiquetado frontal (Res. 810/2021)',
    'norma': 'Resolución 810 de 2021',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  // ─── ASEO — INSUMOS QUÍMICOS (USO ALIMENTARIO) — AMBOS — PROVEEDOR
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_FT_DOSIFICACION',
    'keyApp': 'fichaTecnicaDosificacion',
    'documentoRequerido':
        'Ficha técnica con registro sanitario y dosificaciones (uso alimentario)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': 'INVIMA',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_HOJA_SEGURIDAD',
    'keyApp': 'hojaSeguridad',
    'documentoRequerido': 'Hoja de seguridad (SGA) con 16 parámetros',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_RUT',
    'keyApp': 'rut',
    'documentoRequerido': 'RUT del proveedor',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CAMARA_COMERCIO',
    'keyApp': 'camaraComercio',
    'documentoRequerido': 'Cámara de comercio vigente',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_SOPORTE_REG_SAN',
    'keyApp': 'soporteRegistroInvima',
    'documentoRequerido': 'Soporte de registro sanitario INVIMA',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': 'INVIMA',
    'frecuencia': 'SEGUN_VIGENCIA',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_PLANTA',
    'keyApp': 'actaIvcPlanta',
    'documentoRequerido': 'Acta IVC planta de producción (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': '',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_ACTA_IVC_VEHICULO',
    'keyApp': 'actaIvcVehiculo',
    'documentoRequerido': 'Acta IVC del vehículo transportador (vigencia menor a 1 año)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': '',
    'frecuencia': 'ANUAL',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_SUSTANCIAS_PERMITIDAS',
    'keyApp': 'sustanciasPermitidas',
    'documentoRequerido':
        'Listado/soporte de sustancias permitidas para uso en proceso alimentario',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  // ─── ASEO — INSUMOS QUÍMICOS — AMBOS — RECEPCION
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_FT_DOSIFICACION',
    'keyApp': 'fichaTecnicaDosificacion',
    'documentoRequerido':
        'Ficha técnica con registro sanitario y dosificaciones (copia vigente)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'INSUMOS QUÍMICOS (USO ALIMENTARIO)',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'ROTULADO',
    'codDoc': 'ROT_ETIQUETA_SGA',
    'keyApp': 'rotuladoSGA',
    'documentoRequerido':
        'Etiqueta SGA: pictogramas, palabra de advertencia, H/P, identificación y proveedor (evidencia)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': 'Ley 55 de 1993; Decreto 1496 de 2018',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
  // ─── ASEO — ELEMENTOS DE ASEO — AMBOS — PROVEEDOR
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'ELEMENTOS DE ASEO',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_FICHA_TECNICA',
    'keyApp': 'fichaTecnicaProv',
    'documentoRequerido': 'Ficha técnica del producto',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': '',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'ELEMENTOS DE ASEO',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_RUT',
    'keyApp': 'rut',
    'documentoRequerido': 'RUT del proveedor',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': '',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'ELEMENTOS DE ASEO',
    'origen': 'AMBOS',
    'nivel': 'PROVEEDOR',
    'etapa': 'INICIAL',
    'codDoc': 'PROV_CAMARA_COMERCIO',
    'keyApp': 'camaraComercio',
    'documentoRequerido': 'Cámara de comercio vigente',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': '',
    'entidad': '',
    'frecuencia': 'AL_INICIO/ACTUALIZACION',
  },
  // ─── ASEO — ELEMENTOS DE ASEO — AMBOS — RECEPCION
  {
    'categoriaApp': 'Aseo',
    'materiaPrima': 'ELEMENTOS DE ASEO',
    'origen': 'AMBOS',
    'nivel': 'RECEPCION',
    'etapa': 'CADA_PEDIDO',
    'codDoc': 'PED_FICHA_TECNICA',
    'keyApp': 'fichaTecnica',
    'documentoRequerido': 'Ficha técnica (copia vigente)',
    'obligatorio': 'SI',
    'condicion': '',
    'norma': '',
    'entidad': '',
    'frecuencia': 'POR_PEDIDO',
  },
];

// ══════════════════════════════════════════════════════════════════════════════
// Función de siembra
// ══════════════════════════════════════════════════════════════════════════════

/// Sube los [kReqDocumentosData] a TBL_COMPRAS_REQ_DOCUMENTOS para la empresa.
/// Primero elimina todos los documentos existentes de la empresa, luego
/// inserta los 76 registros de la parametrización v3.
Future<void> sembrarReqDocumentos(
  String empresaId,
  ComprasService svc,
) async {
  final db = FirebaseFirestore.instance;
  final col = db.collection('TBL_COMPRAS_REQ_DOCUMENTOS');

  // 1. Eliminar existentes de la empresa
  final existentes = await col
      .where('empresaId', isEqualTo: empresaId)
      .get();

  // Borrar en lotes de 500
  const batchSize = 499;
  final docsExistentes = existentes.docs;
  for (int i = 0; i < docsExistentes.length; i += batchSize) {
    final batch = db.batch();
    final chunk = docsExistentes.skip(i).take(batchSize);
    for (final d in chunk) {
      batch.delete(d.reference);
    }
    await batch.commit();
  }

  // 2. Insertar nuevos en lotes de 500
  final nuevos = kReqDocumentosData.map((m) {
    final doc = ReqDocumentoDoc(
      empresaId: empresaId,
      categoriaApp: m['categoriaApp'] ?? '',
      materiaPrima: m['materiaPrima'] ?? '',
      origen: m['origen'] ?? 'AMBOS',
      nivel: m['nivel'] ?? 'RECEPCION',
      etapa: m['etapa'] ?? 'CADA_PEDIDO',
      codDoc: m['codDoc'] ?? '',
      keyApp: m['keyApp'] ?? '',
      documentoRequerido: m['documentoRequerido'] ?? '',
      obligatorio: m['obligatorio'] ?? 'SI',
      condicion: m['condicion'] ?? '',
      norma: m['norma'] ?? '',
      entidad: m['entidad'] ?? '',
      frecuencia: m['frecuencia'] ?? '',
      activo: true,
    );
    return doc;
  }).toList();

  for (int i = 0; i < nuevos.length; i += batchSize) {
    final batch = db.batch();
    final chunk = nuevos.skip(i).take(batchSize);
    for (final doc in chunk) {
      batch.set(col.doc(), doc.toMap());
    }
    await batch.commit();
  }
}
